### ISSUE TITLE
Improve the exercise!!

### ISSUE THREAD

**Issue by oneeyedman** [Adalab/m2-evaluacion-intermedia-silviademiguel7#1]
Really cool job @silviademiguel7  !!!

Here you have some tips to improve the exercise:

### Structure

- [x] Define a good structure of folders and files for the project
- [x] Remove unused files/folders from the project: node_modules, package-lock.json

### HTML

- [x] Connect the label to the input using the `for` attribute of the label and the `id` of the input

### Further challenges

Then you can improve the game as you please, here you have some ideas:

- Add new feedback when the number is bigger than 100 or smaller than 0.
- Manage when the user hits the button and the input is empty.
- Make the input work when hitting the enter key.
- Add a reset button that cleans the input, the counter, writes the initial feedback and generates a new random number to play again!
- Whatever you want!

### Call to action

Let me know if you have any doubts ;)

Go for it!!

**Comment by silviademiguel7** [comment]
I have fixed the structure and code of the page.
I have also included the challenges.
When the user enters a value greater than one hundred or below ,the counter does not change.
In case the user does not write any data, the counter does not change, but will be notified.
I have also included the reset button.
Everything is in the master branch
